name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform-setup:
    name: Setup Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

  create-s3-bucket:
    name: Create S3 Bucket
    needs: terraform-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@v0.5.1
        run: terraform init
        # with:
        #   tf_actions_version: 0.14.7
        #   working_dir: .
        #   subcommand: init

      - name: Terraform validate
        uses: hashicorp/terraform-github-actions@v0.5.1
        with:
          tf_actions_version: 0.14.7
          working_dir: .
          subcommand: validate
         
      
      - name: Terraform plan
        uses: hashicorp/terraform-github-actions@v0.5.1
        with:
          tf_actions_version: 0.14.7
          working_dir: .
          subcommand: plan
      
      # - name: Terraform Apply
      #   uses: hashicorp/terraform-github-actions@v0.5.1
      #   with:
      #     tf_actions_version: 0.14.7
      #     working_dir: .
      #     subcommand: "apply"
      #     args: "-auto-approve"


